# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/wvnj828fpihafpmwafsmsxkrzgdr3k9r-cmake-3.8.2/bin/cmake

# The command to remove a file.
RM = /nix/store/wvnj828fpihafpmwafsmsxkrzgdr3k9r-cmake-3.8.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/myrl/Development/ASCIIVN

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/myrl/Development/ASCIIVN

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/nix/store/wvnj828fpihafpmwafsmsxkrzgdr3k9r-cmake-3.8.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/nix/store/wvnj828fpihafpmwafsmsxkrzgdr3k9r-cmake-3.8.2/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/myrl/Development/ASCIIVN/CMakeFiles /home/myrl/Development/ASCIIVN/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/myrl/Development/ASCIIVN/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named asciivn

# Build rule for target.
asciivn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 asciivn
.PHONY : asciivn

# fast build rule for target.
asciivn/fast:
	$(MAKE) -f CMakeFiles/asciivn.dir/build.make CMakeFiles/asciivn.dir/build
.PHONY : asciivn/fast

asciibuffer.o: asciibuffer.c.o

.PHONY : asciibuffer.o

# target to build an object file
asciibuffer.c.o:
	$(MAKE) -f CMakeFiles/asciivn.dir/build.make CMakeFiles/asciivn.dir/asciibuffer.c.o
.PHONY : asciibuffer.c.o

asciibuffer.i: asciibuffer.c.i

.PHONY : asciibuffer.i

# target to preprocess a source file
asciibuffer.c.i:
	$(MAKE) -f CMakeFiles/asciivn.dir/build.make CMakeFiles/asciivn.dir/asciibuffer.c.i
.PHONY : asciibuffer.c.i

asciibuffer.s: asciibuffer.c.s

.PHONY : asciibuffer.s

# target to generate assembly for a file
asciibuffer.c.s:
	$(MAKE) -f CMakeFiles/asciivn.dir/build.make CMakeFiles/asciivn.dir/asciibuffer.c.s
.PHONY : asciibuffer.c.s

asciibufferfill.o: asciibufferfill.c.o

.PHONY : asciibufferfill.o

# target to build an object file
asciibufferfill.c.o:
	$(MAKE) -f CMakeFiles/asciivn.dir/build.make CMakeFiles/asciivn.dir/asciibufferfill.c.o
.PHONY : asciibufferfill.c.o

asciibufferfill.i: asciibufferfill.c.i

.PHONY : asciibufferfill.i

# target to preprocess a source file
asciibufferfill.c.i:
	$(MAKE) -f CMakeFiles/asciivn.dir/build.make CMakeFiles/asciivn.dir/asciibufferfill.c.i
.PHONY : asciibufferfill.c.i

asciibufferfill.s: asciibufferfill.c.s

.PHONY : asciibufferfill.s

# target to generate assembly for a file
asciibufferfill.c.s:
	$(MAKE) -f CMakeFiles/asciivn.dir/build.make CMakeFiles/asciivn.dir/asciibufferfill.c.s
.PHONY : asciibufferfill.c.s

asciibufferssim.o: asciibufferssim.c.o

.PHONY : asciibufferssim.o

# target to build an object file
asciibufferssim.c.o:
	$(MAKE) -f CMakeFiles/asciivn.dir/build.make CMakeFiles/asciivn.dir/asciibufferssim.c.o
.PHONY : asciibufferssim.c.o

asciibufferssim.i: asciibufferssim.c.i

.PHONY : asciibufferssim.i

# target to preprocess a source file
asciibufferssim.c.i:
	$(MAKE) -f CMakeFiles/asciivn.dir/build.make CMakeFiles/asciivn.dir/asciibufferssim.c.i
.PHONY : asciibufferssim.c.i

asciibufferssim.s: asciibufferssim.c.s

.PHONY : asciibufferssim.s

# target to generate assembly for a file
asciibufferssim.c.s:
	$(MAKE) -f CMakeFiles/asciivn.dir/build.make CMakeFiles/asciivn.dir/asciibufferssim.c.s
.PHONY : asciibufferssim.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/asciivn.dir/build.make CMakeFiles/asciivn.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/asciivn.dir/build.make CMakeFiles/asciivn.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/asciivn.dir/build.make CMakeFiles/asciivn.dir/main.c.s
.PHONY : main.c.s

testimage.o: testimage.c.o

.PHONY : testimage.o

# target to build an object file
testimage.c.o:
	$(MAKE) -f CMakeFiles/asciivn.dir/build.make CMakeFiles/asciivn.dir/testimage.c.o
.PHONY : testimage.c.o

testimage.i: testimage.c.i

.PHONY : testimage.i

# target to preprocess a source file
testimage.c.i:
	$(MAKE) -f CMakeFiles/asciivn.dir/build.make CMakeFiles/asciivn.dir/testimage.c.i
.PHONY : testimage.c.i

testimage.s: testimage.c.s

.PHONY : testimage.s

# target to generate assembly for a file
testimage.c.s:
	$(MAKE) -f CMakeFiles/asciivn.dir/build.make CMakeFiles/asciivn.dir/testimage.c.s
.PHONY : testimage.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... asciivn"
	@echo "... asciibuffer.o"
	@echo "... asciibuffer.i"
	@echo "... asciibuffer.s"
	@echo "... asciibufferfill.o"
	@echo "... asciibufferfill.i"
	@echo "... asciibufferfill.s"
	@echo "... asciibufferssim.o"
	@echo "... asciibufferssim.i"
	@echo "... asciibufferssim.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... testimage.o"
	@echo "... testimage.i"
	@echo "... testimage.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

